

FROM python:3.7

EXPOSE 8080

COPY requirements.txt requirements.txt
RUN pip install -U pip
RUN pip install -r requirements.txt

COPY . .
WORKDIR /

# Run
ENTRYPOINT [“streamlit”, “run”, app.py”, “–server.port=8080”, “–server.address=0.0.0.0”]